# Generated by Django 6.0.4 on 2026-04-14 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=36, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("book_url", models.URLField(max_length=500, unique=True)),
                ("cover_url", models.URLField(blank=True, max_length=500, null=True)),
                ("publish_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "first_publish_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("number_of_pages", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "rating_average",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("rating_count", models.PositiveIntegerField(blank=True, null=True)),
                ("subjects", models.TextField(blank=True, null=True)),
                ("subject_places", models.TextField(blank=True, null=True)),
                ("subject_times", models.TextField(blank=True, null=True)),
                ("subject_people", models.TextField(blank=True, null=True)),
                (
                    "olid",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "ol_edition_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ol_work_id", models.CharField(blank=True, max_length=20, null=True)),
                ("isbn_10", models.CharField(blank=True, max_length=10, null=True)),
                ("isbn_13", models.CharField(blank=True, max_length=13, null=True)),
                ("preview_url", models.URLField(blank=True, max_length=500, null=True)),
                ("ai_summary", models.TextField(blank=True, null=True)),
                (
                    "ai_sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "ai_sentiment_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="books_book_title_d3218d_idx"),
                    models.Index(
                        fields=["author"], name="books_book_author_b941fe_idx"
                    ),
                    models.Index(fields=["olid"], name="books_book_olid_19ff99_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("sources", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="books.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_text", models.TextField()),
                ("chunk_index", models.PositiveIntegerField()),
                ("chroma_id", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "ordering": ["book", "chunk_index"],
                "unique_together": {("book", "chunk_index")},
            },
        ),
    ]
